### ISSUE TITLE
Node Module Not Found

### ISSUE THREAD

**Issue by jigar-bitani** [Adamant-im/adamant-tradebot#14]
Hello

I have cloned the repository and installed node modules using npm I. After setting up the config file, once I execute the command

pm2 start --name tradebot app.js

It is throwing errors 

`Error: Cannot find module 'adamant-api/helpers/keys'
Require stack:
- <ProjectPath>adamant-tradebot\modules\configReader.js
- <ProjectPath>adamant-tradebot\helpers\notify.js
- <ProjectPath>adamant-tradebot\app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Module.Hook._require.Module.require (<ProfilePath>AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:61:29)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (<ProjectPath>adamant-tradebot\modules\configReader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (<ProfilePath>AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '<ProjectPath>adamant-tradebot\\modules\\configReader.js',
    '<ProjectPath>adamant-tradebot\\helpers\\notify.js',
    '<ProjectPath>adamant-tradebot\\app.js'
  ]
}`

Can someone help?

Thanks

**Comment by jigar-bitani** [comment]
There are some recent changes in the adamant-api package.  In the configReader.js, need to make the following change.

const keys = require('adamant-api/src/helpers/keys');

Thanks

**Comment by adamant-al** [comment]
Hi!
Fixed in v5.0.0: https://github.com/Adamant-im/adamant-tradebot/releases/tag/v5.0.0
